# Generated by Django 4.1 on 2022-08-27 18:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Pon el nombre del director', max_length=30)),
                ('estado', models.CharField(blank=True, choices=[('a', 'Activo'), ('p', 'Parado'), ('j', 'Jubilado')], default='a', help_text='Se encuenta activo, parado o jubilado', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Peliculas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('titulo', models.CharField(help_text='Pon el nombre de la película', max_length=100)),
                ('descripcion', models.TextField(help_text='Escribe una breve descripción de la película', max_length=500)),
                ('director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='directores.directores')),
                ('genero', models.ManyToManyField(to='directores.genero')),
            ],
        ),
    ]
